# AC (secteur) : 5 min DPMS, 10 min lock, 5h suspend
timeout 300 'swaymsg "output * power off"' resume 'swaymsg "output * power on"'
timeout 600 '~/.local/bin/sway-lock'
timeout 18000 'systemctl suspend -i'
before-sleep '~/.local/bin/sway-lock'
