# AC (secteur) :
# - 10 min : lock
# - 11 min : écran off
# - pas de suspend automatique
# - before-sleep : lock systématique AVANT tout suspend manuel
timeout 600 '~/.local/bin/sway-lock'
timeout 660 'swaymsg "output * power off"' resume 'swaymsg "output * power on"'
before-sleep '~/.local/bin/sway-lock'
lock '~/.local/bin/sway-lock'
