# AC (secteur) :
# - 10 min : lock
# - 11 min : écran off
# - 5 h    : suspend
# - before-sleep : lock systématique AVANT suspend
timeout 600 '~/.local/bin/sway-lock'
timeout 660 'swaymsg "output * power off"' resume 'swaymsg "output * power on"'
timeout 18000 'systemctl suspend -i'
before-sleep '~/.local/bin/sway-lock'
lock '~/.local/bin/sway-lock'
