# Batterie :
# - 4 min  : lock
# - 5 min  : écran off
# - 20 min : suspend
# - before-sleep : lock systématique AVANT suspend
timeout 240 '~/.local/bin/sway-lock'
timeout 300 'swaymsg "output * power off"' resume 'swaymsg "output * power on"'
timeout 1200 'systemctl suspend -i'
before-sleep '~/.local/bin/sway-lock'
lock '~/.local/bin/sway-lock'
