[Login]
# Fermeture capot sur AC : rien
HandleLidSwitchExternalPower=ignore
# Fermeture capot sur batterie : suspend
HandleLidSwitch=suspend
# Fermeture capot quand docké (station d'accueil) : rien
HandleLidSwitchDocked=ignore
